### ISSUE TITLE
Can not open map after packaging by Pyinstaller

### ISSUE THREAD

**Issue by craigstar** [skylarkdrones/pyqtlet#23]
Can not open map after packaging by Pyinstaller. Error code below.
```
js: Uncaught ReferenceError: QWebChannel is not defined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'on' of undefined
js: Uncaught TypeError: Cannot read property 'on' of undefined
js: Uncaught TypeError: Cannot read property 'on' of undefined
js: Uncaught TypeError: Cannot read property 'setView' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught ReferenceError: L is not defined
js: Uncaught ReferenceError: L is not defined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'bindPopup' of undefined
js: Uncaught TypeError: Cannot read property 'bindPopup' of undefined
js: Uncaught TypeError: Cannot read property 'bindPopup' of undefined
js: Uncaught TypeError: Cannot read property 'bindPopup' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addControl' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addControl' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'addLayer' of undefined
js: Uncaught TypeError: Cannot read property 'addControl' of undefined
js: Uncaught ReferenceError: L is not defined
js: Uncaught TypeError: Cannot read property 'on' of undefined
js: Uncaught TypeError: Cannot read property 'addControl' of undefined
js: Uncaught ReferenceError: L is not defined
```

My code:
```
from pyqtlet import L, MapWidget

class BaseMapWidget(MapWidget):
    """docstring for BaseMapWidget"""
    def __init__(self, parent=None):
        super(BaseMapWidget, self).__init__(parent)
        self.map = L.map(self)
        # default view
        self.map.setView([39.73, -104.99], 1)
```

My environment is Ubuntu 14.04, conda python3.6. And related packages below:
```
pyqt                      5.9.2            py36h05f1152_2  
pyqt5-sip                 4.19.14                  pypi_0    pypi
pyinstaller               3.3.1                    py36_0    conda-forge
```

**Comment by samhattangady** [comment]
So `pyqtlet` packages some javascript files along with it (in `pyqtlet/web/modules`). It looks like those aren't available in your packaging. You'll have to see how those can be included along with the rest in pyinstaller.

**Comment by craigstar** [comment]
you mean by default Pyinstaller does not pack JS files? Have you tried to package by Pyinstaller? I don't know where to start. My pyqtlet is the default one. I really need to pack my app.

It works perfect when I use python command to start it. (maybe very little chances it crashes like above, but when I close and restart it, the map comes back again.)

**Comment by samhattangady** [comment]
Okay. I used `pyinstaller` and faced the same problem. It looks like `pyinstaller` is not able to find and include all the files that are needed.

Can you try using `cx_freeze`. I used that, and it worked out of the box.

**Comment by craigstar** [comment]
Thank you! I try cx_freeze on Ubuntu, 
`1st.` that opengl problem came again. I fixed it according to my previous closed issue.
`2nd.` when I pack with `cx_freeze`, this time, an opengl `NoneTpye object is not callable` something error occured. I fixed this by hacking OpenGL source code.(don't know why, but it worked.)
`3rd. `Now I can run my compiled program. However!!!! it worked just in my own laptop. When I copy it to another ubuntu system. PyQt5 error occured. I'm going crazy!!

Well, I think this is not pyqtlet's problem. Just to let people know.

**Comment by craigstar** [comment]
@samhattangady I finally found out the problem why Pyinstaller fail to load pyqtlet. It's simple actually. 
By digging in, I found an absolute path `html_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'web', 'map.html')`
after deploying, that `html_path` will be wrong! 

So maybe you could fix this absolute path problem.

**Comment by samhattangady** [comment]
@craigstar Hey. I did not realize that the absolute paths could cause a bug. Thanks for finding that one. Were you able to fix it?

We have been using `cx_freeze` executables in production for a while, and have never seen any of the bugs that you mention. Specifically the opengl bugs.

For reference, we are running Ubuntu 18.04, python 3.6.5 and pyqt5==5.11.2.
On production, I believe we are running pyqtlet==0.3.0 and pyqtlet==0.3.3. Try both of those and see if it resolves any of the issues you are facing.

**Comment by craigstar** [comment]
@samhattangady hey, I'm sorry that I found it was my mistake. Pyinstaller by default will not include pyqtlet, but I can specify pyqtlet's path and tell Pyinstaller to pack it together. So it's not a problem.

**Comment by krnekhelesh** [comment]
Closing this issue as the fix is required in the 3rd party module Pyinstaller.

**Comment by louisdelaune** [comment]
Hey I'm having a similar problem but it gives me a file not found error and for context I'm using fbs and it works with fbs run but not when I compile it, anyone have any suggestions?

**Comment by hasanbdimran** [comment]
The easier solution is to try to find the directory where pyqtlet is installed. Then copy paste the whole folder into the dist folder.
