### ISSUE TITLE
Can`t get drawn shape coordinates after editing in leaflet.draw

### ISSUE THREAD

**Issue by HamzaKandil** [skylarkdrones/pyqtlet#28]
Hi, @samhattangady 

I can`t wrap my head around this issue, I`m drawing shapes on the map using L.Draw plugin, after finishing the drawing, the drawCreated event is initialized and I print the shape coordinates. 

The issue is: when I press the edit button and change the shape geometry,, then press 'save', the new coordinates are not printed. I tried to add event of draw:editstop and it`s added, but I can`t get the geometry of the new shape. 

your help is much appreciated.

**Comment by samhattangady** [comment]
Hey, can you please share the smallest code sample that has the issue, and I can help you out.

It looks like the draw:edit event is not supported, I would suggest using some other event that is.

Otherwise you can add an event;
Just see how drawCreated event is created in https://github.com/skylarkdrones/pyqtlet/blob/master/pyqtlet/leaflet/map/map.py

You would need to create a pyqtsignal, a pyqtslot, and link them in __init__.

If you make this change, please create a pull request as well. Thanks.

**Comment by HamzaKandil** [comment]
Thanks for your reply 

I already added a couple of events. I added (draw:editstart), which launches when I press the toolbar edit button. I also added the (draw:editstop), which launches when I save the editing. Both events return the layer type and the event name. 

What I want to do is to print the coordinates of the edited shape same as the (draw:created) event, which returns a polygon with the coordinates of each corner. 
I tried a naive approach, to connect the (draw:editstop) slot to (draw:created) event, which led to the map crahsing when I save the edit :) 

I really can't get my head around this, ur help will be much appreciated.

**Comment by samhattangady** [comment]
Can you please share a minimal code sample?

**Comment by HamzaKandil** [comment]
These are the lines I added to the map.py file: 

class Map(Evented):

```
clicked = pyqtSignal(dict)
zoom = pyqtSignal(dict)
drawCreated = pyqtSignal(dict)
drawEditStop = pyqtSignal(dict)
```

Then, below the _ondrawCreated function: 

```
@pyqtSlot(QJsonValue)
def _onDrawEditStop(self, event):
    self._logger.debug('draw editstop. event: {event}'.format(event=event))
    self.drawEditStop.emit(self._qJsonValueToDict(event))
```

Finally, below the __init__: 

`self._connectEventToSignal('draw:editstop', '_onDrawEditStop')`
___________________________________________________________________________

In my main code, this is the line to call the event: 

`self.map.drawEditStop.connect(lambda x: print(x))  `

which returns the following: 
{'handler': 'edit', 'type': 'draw:editstop'}

my question is: 
How can I access the drawn shape coordinates after the edit? 
Thanks.

**Comment by samhattangady** [comment]
In this case, you would have to create a function / method that uses the coordinates.

then, you can call self.map.drawEditStop.connect(self.handleCoordinates).

If you share a repo with the code, I would be able to help you more.

Also if you have a js example, you might be able to use `getJsResponse` to access the data that you need.

**Comment by samhattangady** [comment]
Also I noticed that the editstop function from leaflet draw does not return coordinates.
https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#l-draw-event-draw:editstop

You should use the editstop function to trigger a `toGeoJSON` from the featuregroup that is available in L.Draw.featuregroup.

**Comment by HamzaKandil** [comment]
Thanks for your help, really appreciate it. 

I added this to the code: 
`self.map.drawEditStop.connect(foo)  #`

then, the foo function declaration: 
```
def foo():
    print("hahaha")
    self.drawControl.featureGroup.toGeoJSON(lambda x: print(x))

```
which returned the edited coordinates. 
I`ll add the other L.Draw events and make a pull request. will also share a repo as soon as I finish my project. 
Thanks
