### ISSUE TITLE
gray map for second instance

### ISSUE THREAD

**Issue by danielhrisca** [skylarkdrones/pyqtlet#34]
Hello,

I'm trying to use pyqtlet in an application were there could be multiple QMDISubWindows that contain maps. The first map is displayed correctly, but the next one are looking gray. Even if I close all the existing maps, creating new maps afterwards result in gray area.

![image](https://user-images.githubusercontent.com/20952040/134768600-9935086a-bc6b-4561-820d-b15a6f1ac90f.png)

Here is the source code for the GPS widget that contains the map: https://github.com/danielhrisca/asammdf/blob/development/asammdf/gui/widgets/gps.py

@JaWeilBaum  and others:
Any idea what I am doing wrong?

**Comment by atanx** [comment]
@danielhrisca  

Currently, due to Evented class has a  class attribute 'mapWidget'. only one map could be shown correctly. 
https://github.com/skylarkdrones/pyqtlet/blob/2242f63b0dce6dd6357aaa0c6fe23a991451bfdd/pyqtlet/leaflet/core/evented.py#L9-L47

**Comment by danielhrisca** [comment]
To whom it may concern, the fix for this is to set `leaflet.core.Evented.mapWidget = None` before creating a new `MapWidget` object

see https://github.com/danielhrisca/asammdf/blob/b8804aed9e87e9ef3cd94b1ea1c17959d603239e/asammdf/gui/widgets/gps.py#L59
